version: "3"

services:
  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassw0rd
      - MYSQL_DATABASE=gqlprime
      - MYSQL_USER=gqlprime-rw
      - MYSQL_PASSWORD=passw0rd
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - '3306:3306'

volumes:
  mysql:
    driver: local